# Generated by Django 5.1 on 2026-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (English)')),
                ('title_uz', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Uzbek)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Russian)')),
                ('issuer_en', models.CharField(blank=True, max_length=200, verbose_name='Issuer (English)')),
                ('issuer_uz', models.CharField(blank=True, max_length=200, verbose_name='Issuer (Uzbek)')),
                ('issuer_ru', models.CharField(blank=True, max_length=200, verbose_name='Issuer (Russian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Image')),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/docs/', verbose_name='Document (PDF)')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='Issued on')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Interest (English)')),
                ('label_uz', models.CharField(blank=True, default='', max_length=200, verbose_name='Interest (Uzbek)')),
                ('label_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Interest (Russian)')),
                ('detail_en', models.TextField(blank=True, verbose_name='Detail (English)')),
                ('detail_uz', models.TextField(blank=True, verbose_name='Detail (Uzbek)')),
                ('detail_ru', models.TextField(blank=True, verbose_name='Detail (Russian)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Photo')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Full name (English)')),
                ('full_name_uz', models.CharField(blank=True, default='', max_length=200, verbose_name='Full name (Uzbek)')),
                ('full_name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Full name (Russian)')),
                ('headline_en', models.CharField(blank=True, max_length=300, verbose_name='Headline (English)')),
                ('headline_uz', models.CharField(blank=True, max_length=300, verbose_name='Headline (Uzbek)')),
                ('headline_ru', models.CharField(blank=True, max_length=300, verbose_name='Headline (Russian)')),
                ('about_en', models.TextField(blank=True, verbose_name='About (English)')),
                ('about_uz', models.TextField(blank=True, verbose_name='About (Uzbek)')),
                ('about_ru', models.TextField(blank=True, verbose_name='About (Russian)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Phone')),
                ('location_en', models.CharField(blank=True, max_length=200, verbose_name='Location (English)')),
                ('location_uz', models.CharField(blank=True, max_length=200, verbose_name='Location (Uzbek)')),
                ('location_ru', models.CharField(blank=True, max_length=200, verbose_name='Location (Russian)')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume profile',
                'verbose_name_plural': 'Resume profile',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('grand_vine', 'Grand vine'), ('wild_canopy', 'Wild canopy'), ('warm_earth', 'Warm earth'), ('avant_hall', 'Avant hall'), ('art_stage', 'Art stage'), ('bold_view', 'Bold view'), ('pure_craft', 'Pure craft'), ('dark_lens', 'Dark lens'), ('neon_beat', 'Neon beat')], default='grand_vine', max_length=32, verbose_name='Site theme')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
