# Generated by Django 6.0.3 on 2026-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Institution (English)')),
                ('institution_uz', models.CharField(blank=True, default='', max_length=300, verbose_name='Institution (Uzbek)')),
                ('institution_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Institution (Russian)')),
                ('degree_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Degree (English)')),
                ('degree_uz', models.CharField(blank=True, default='', max_length=300, verbose_name='Degree (Uzbek)')),
                ('degree_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Degree (Russian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['sort_order', '-start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Company (English)')),
                ('company_uz', models.CharField(blank=True, default='', max_length=200, verbose_name='Company (Uzbek)')),
                ('company_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Company (Russian)')),
                ('role_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Role (English)')),
                ('role_uz', models.CharField(blank=True, default='', max_length=300, verbose_name='Role (Uzbek)')),
                ('role_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Role (Russian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current role')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Work experience',
                'verbose_name_plural': 'Work experience',
                'ordering': ['sort_order', '-start_date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='skills_en',
            field=models.TextField(blank=True, default='', verbose_name='Skills (English)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='skills_ru',
            field=models.TextField(blank=True, default='', verbose_name='Skills (Russian)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='skills_uz',
            field=models.TextField(blank=True, default='', verbose_name='Skills (Uzbek)'),
        ),
    ]
