# Generated by Django 5.1 on 2026-03-29 09:21

from django.db import migrations, models


def _first(*vals):
    for v in vals:
        if v and str(v).strip():
            return str(v).strip()
    return ""


def backfill_source_fields(apps, schema_editor):
    ResumeProfile = apps.get_model("resume", "ResumeProfile")
    for o in ResumeProfile.objects.all():
        if not _first(o.full_name):
            o.full_name = _first(o.full_name_en, o.full_name_uz, o.full_name_ru)[:200]
        if not _first(o.headline):
            o.headline = _first(o.headline_en, o.headline_uz, o.headline_ru)[:300]
        if not _first(o.about):
            o.about = _first(o.about_en, o.about_uz, o.about_ru) or ""
        if not _first(o.location):
            o.location = _first(o.location_en, o.location_uz, o.location_ru)[:200]
        if not _first(o.skills):
            o.skills = _first(o.skills_en, o.skills_uz, o.skills_ru) or ""
        o.save(update_fields=["full_name", "headline", "about", "location", "skills"])

    Certificate = apps.get_model("resume", "Certificate")
    for o in Certificate.objects.all():
        if not _first(o.title):
            o.title = _first(o.title_en, o.title_uz, o.title_ru)[:300]
        if not _first(o.issuer):
            o.issuer = _first(o.issuer_en, o.issuer_uz, o.issuer_ru)[:200]
        if not _first(o.description):
            o.description = _first(o.description_en, o.description_uz, o.description_ru) or ""
        o.save(update_fields=["title", "issuer", "description"])

    WorkExperience = apps.get_model("resume", "WorkExperience")
    for o in WorkExperience.objects.all():
        if not _first(o.company):
            o.company = _first(o.company_en, o.company_uz, o.company_ru)[:200]
        if not _first(o.role):
            o.role = _first(o.role_en, o.role_uz, o.role_ru)[:300]
        if not _first(o.description):
            o.description = _first(o.description_en, o.description_uz, o.description_ru) or ""
        o.save(update_fields=["company", "role", "description"])

    Education = apps.get_model("resume", "Education")
    for o in Education.objects.all():
        if not _first(o.institution):
            o.institution = _first(o.institution_en, o.institution_uz, o.institution_ru)[:300]
        if not _first(o.degree):
            o.degree = _first(o.degree_en, o.degree_uz, o.degree_ru)[:300]
        if not _first(o.description):
            o.description = _first(o.description_en, o.description_uz, o.description_ru) or ""
        o.save(update_fields=["institution", "degree", "description"])

    Interest = apps.get_model("resume", "Interest")
    for o in Interest.objects.all():
        if not _first(o.label):
            o.label = _first(o.label_en, o.label_uz, o.label_ru)[:200]
        if not _first(o.detail):
            o.detail = _first(o.detail_en, o.detail_uz, o.detail_ru) or ""
        o.save(update_fields=["label", "detail"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_profile_skills_experience_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description (source)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Issuer (source)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Title (source)'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Degree (source)'),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description (source)'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Institution (source)'),
        ),
        migrations.AddField(
            model_name='interest',
            name='detail',
            field=models.TextField(blank=True, default='', verbose_name='Detail (source)'),
        ),
        migrations.AddField(
            model_name='interest',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Interest (source)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='About (source / default)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Full name (source / default)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Headline (source / default)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Location (source / default)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='skills',
            field=models.TextField(blank=True, default='', verbose_name='Skills (source / default)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Company (source)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description (source)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Role (source)'),
        ),
        migrations.RunPython(backfill_source_fields, noop_reverse),
    ]
