# Generated by Django 6.0.3 on 2026-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_source_fields_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (optional)')),
                ('url', models.URLField(verbose_name='Project URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Preview image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Portfolio item',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
