# Generated by Django 6.0.3 on 2026-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram (username or link)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram (username or link)'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='WhatsApp (phone number)'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
