# Generated by Django 6.0.3 on 2026-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_profile_contact_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Label (e.g. Discord)')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, choices=[('link', 'Link (default)'), ('globe', 'Globe / website'), ('chat', 'Chat / messenger'), ('users', 'Community / team'), ('video', 'Video / stream'), ('code', 'Code / dev'), ('device', 'Mobile app'), ('musical', 'Music / audio'), ('sparkles', 'Other highlights'), ('hashtag', 'Social / topics')], max_length=32, null=True, verbose_name='Icon (optional)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Extra contact link',
                'verbose_name_plural': 'Extra contact links',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
