# Generated by Django 5.0.14 on 2026-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_contact_link_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='kwork',
            field=models.URLField(blank=True, null=True, verbose_name='Kwork'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('grand_vine', 'Grand vine'), ('wild_canopy', 'Wild canopy'), ('warm_earth', 'Warm earth'), ('avant_hall', 'Avant hall'), ('art_stage', 'Art stage'), ('bold_view', 'Bold view'), ('pure_craft', 'Pure craft'), ('dark_lens', 'Dark lens'), ('neon_beat', 'Neon beat'), ('red', 'Red / Qizil / Красный'), ('pink', 'Pink / Pushti / Розовый')], default='grand_vine', max_length=32, verbose_name='Site theme'),
        ),
    ]
