# Generated by Django 5.0.14 on 2026-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resumeprofile_kwork_alter_sitesettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description (source)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Description (Uzbek)'),
        ),
    ]
