# Generated by Django 5.0.14 on 2026-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_sitesettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='work_bg_color',
            field=models.CharField(default='#cccccc', max_length=7, verbose_name='WORK text color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_bg_opacity',
            field=models.IntegerField(default=5, verbose_name='WORK text opacity'),
        ),
    ]
