# Generated by Django 5.0.14 on 2026-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_sitesettings_work_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Masalan: nav_contact, cta_resume', max_length=80, unique=True, verbose_name='Kalit')),
                ('text_uz', models.CharField(blank=True, default='', max_length=500, verbose_name="O'zbekcha")),
                ('text_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Inglizcha')),
                ('text_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Ruscha')),
            ],
            options={
                'verbose_name': 'Sayt matni',
                'verbose_name_plural': 'Sayt matnlari',
                'ordering': ['key'],
            },
        ),
    ]
