# Generated by Django 5.0.14 on 2026-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_seed_ui_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Uzbek)'),
        ),
    ]
