# Generated by Django 5.0.14 on 2026-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_add_portfolio_title_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (source)')),
                ('title_en', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (English)')),
                ('title_uz', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Uzbek)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Title (Russian)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description (source)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma separated tags, e.g., Python, Django, REST API', max_length=500, verbose_name='Tags')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
