# Generated by Django 5.0.3 on 2026-06-21 10:18

from django.db import migrations

def add_services(apps, schema_editor):
    Service = apps.get_model('resume', 'Service')
    services = [
        {
            "title": "Backend Development",
            "title_uz": "Backend Dasturlash",
            "title_ru": "Backend Разработка",
            "description": "I build scalable and secure backend systems using Python and Django. Creating robust RESTful APIs, optimizing database queries, and ensuring high performance for web applications.",
            "description_uz": "Men Python va Django yordamida kengayadigan va xavfsiz backend tizimlarini yarataman. Kuchli RESTful API'lar ishlab chiqish, ma'lumotlar bazasi so'rovlarini optimallashtirish va veb ilovalar uchun yuqori unumdorlikni ta'minlash.",
            "description_ru": "Я создаю масштабируемые и безопасные бэкенд-системы с использованием Python и Django. Разработка надежных RESTful API, оптимизация запросов к базе данных и обеспечение высокой производительности для веб-приложений.",
            "tags": "Python, Django, REST API, PostgreSQL",
            "sort_order": 1
        },
        {
            "title": "Telegram Bots",
            "title_uz": "Telegram Botlar",
            "title_ru": "Telegram Боты",
            "description": "Development of complex Telegram bots with AI integration, payment systems, and admin dashboards to automate your business processes.",
            "description_uz": "Sizning biznes jarayonlaringizni avtomatlashtirish uchun sun'iy intellekt, to'lov tizimlari va admin panellari bilan integratsiya qilingan murakkab Telegram botlarini ishlab chiqish.",
            "description_ru": "Разработка сложных Telegram ботов с интеграцией ИИ, платежными системами и админ-панелями для автоматизации ваших бизнес-процессов.",
            "tags": "Aiogram, Telebot, Celery, Redis",
            "sort_order": 2
        },
        {
            "title": "Web Scraping & Automation",
            "title_uz": "Web Scraping va Avtomatlashtirish",
            "title_ru": "Веб Скрапинг и Автоматизация",
            "description": "Extracting valuable data from websites and automating repetitive tasks to save your time and resources.",
            "description_uz": "Veb-saytlardan qimmatli ma'lumotlarni yig'ish va vaqtingiz hamda resurslaringizni tejash uchun takrorlanuvchi vazifalarni avtomatlashtirish.",
            "description_ru": "Извлечение ценных данных с веб-сайтов и автоматизация повторяющихся задач для экономии вашего времени и ресурсов.",
            "tags": "BeautifulSoup, Selenium, Scrapy",
            "sort_order": 3
        }
    ]
    for s in services:
        Service.objects.create(**s)

def remove_services(apps, schema_editor):
    Service = apps.get_model('resume', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_add_service_model'),
    ]

    operations = [
        migrations.RunPython(add_services, remove_services),
    ]
