# Generated by Django 5.0.14 on 2026-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_add_dummy_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
    ]
