# Generated by Django 5.0.14 on 2026-06-21 12:38

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_add_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, null=True, storage=resume.models.get_pdf_storage, upload_to='certificates/docs/', verbose_name='Document (PDF)'),
        ),
    ]
