# Generated by Django 5.0.14 on 2026-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_certificate_pdf_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_color',
            field=models.CharField(default='#0a0a0a', help_text="Hero bo'limining orqa fon rangi. Masalan: #0a0a0a (qora), #0d1b2a (to'q ko'k)", max_length=7, verbose_name='Hero fon rangi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_color',
            field=models.CharField(default='#ffffff', help_text="Hero bo'limidagi 'DEVELOPER' yozuvi rangi. Masalan: #ffffff (oq), #f0f0f0", max_length=7, verbose_name='Hero matn rangi'),
        ),
    ]
