# Generated by Django 5.0.14 on 2026-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_add_hero_colors_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_label',
            field=models.CharField(default='Client Satisfaction', help_text='Masalan: Mijozlar mamnuniyati', max_length=60, verbose_name='1-statistika nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_value',
            field=models.CharField(default='98%', help_text='Masalan: 98%, 50+, 3 yil', max_length=20, verbose_name='1-statistika qiymati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_label',
            field=models.CharField(default='Projects Done', help_text='Masalan: Bajarilgan loyihalar', max_length=60, verbose_name='2-statistika nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_value',
            field=models.CharField(default='25+', help_text='Masalan: 25+, 10, 100+', max_length=20, verbose_name='2-statistika qiymati'),
        ),
    ]
