# Generated by Django 5.0.14 on 2026-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_add_hero_stats_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_label_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='1-statistika nomi (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_label_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='1-statistika nomi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_label_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='1-statistika nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_value_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='1-statistika qiymati (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_value_ru',
            field=models.CharField(blank=True, max_length=20, verbose_name='1-statistika qiymati (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_value_uz',
            field=models.CharField(blank=True, max_length=20, verbose_name='1-statistika qiymati (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_label_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='2-statistika nomi (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_label_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='2-statistika nomi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_label_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='2-statistika nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_value_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='2-statistika qiymati (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_value_ru',
            field=models.CharField(blank=True, max_length=20, verbose_name='2-statistika qiymati (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_value_uz',
            field=models.CharField(blank=True, max_length=20, verbose_name='2-statistika qiymati (UZ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_stat1_label',
            field=models.CharField(default='Client Satisfaction', max_length=60, verbose_name='1-statistika nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_stat1_value',
            field=models.CharField(default='98%', max_length=20, verbose_name='1-statistika qiymati'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_stat2_label',
            field=models.CharField(default='Projects Done', max_length=60, verbose_name='2-statistika nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_stat2_value',
            field=models.CharField(default='25+', max_length=20, verbose_name='2-statistika qiymati'),
        ),
    ]
