# Generated by Django 5.0.14 on 2026-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_update_hero_stats_to_i18n_fields_proper'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_greeting',
            field=models.CharField(default='👋 Salom, men Matyoqubov Rasulbek', max_length=150, verbose_name='Salomlashish matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_greeting_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Salomlashish matni (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_greeting_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Salomlashish matni (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_greeting_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Salomlashish matni (UZ)'),
        ),
    ]
