# Generated by Django 5.0.14 on 2026-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_seed_profile_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured (Asosiy yutuq)'),
        ),
    ]
