# Generated by Django 5.0.14 on 2026-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_certificate_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='featured_badge_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Featured badge text (source)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='featured_badge_text_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Featured badge text (English)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='featured_badge_text_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Featured badge text (Russian)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='featured_badge_text_uz',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Featured badge text (Uzbek)'),
        ),
    ]
